"""
====================================================================================================
   AI DOCUMENT TRANSLATOR (ENGINEERING EDITION)
====================================================================================================

1. CORE METHODOLOGY: THE "DIGITAL TWIN" ARCHITECTURE
   -------------------------------------------------------------------------------------------------
   This application operates as a Document Reconstruction Engine, utilizing a "Digital Twin" approach
   to treat .docx files as hierarchical XML structures rather than flat text strings.

   - ATOMIC DISSECTION & XML PARSING (NAMESPACE SAFE):
     Uses `python-docx` and custom lxml handlers to surgically parse paragraphs and runs.
     Crucially, it utilizes a `robust_xml_copy` mechanism that preserves distinct XML namespaces 
     (nsmap), ensuring MathType equations (m:oMath), Citations, and SEQ/REF fields remain 
     functional after reconstruction.

   - VISUAL DNA & COLOR PRESERVATION:
     Before translation, the engine maps the "Visual DNA" of every text segment.
     It detects Font Colors (Hex Codes), Bold, Italic, and Super/Subscript, injecting
     them as semantic tags ({c:FF0000}, {b}) to ensure 100% visual fidelity in the output.

   - GLOBAL CONTEXT & ADAPTIVE MEMORY:
     The engine performs a "Smart Scan" to establish a Global Document Context (Domain + Tone).
     It utilizes an "Adaptive Context Window" (Rolling Buffer) that maintains the last 2000 characters 
     of translation history to ensure terminological consistency across long documents.

   - DYNAMIC FIELD PRESERVATION (RECOVERABLE TOKENS):
     The engine extracts complex XML fields as immutable tokens ({{FLD_x}}). The reconstruction 
     logic uses a "Robust Token Pattern" that recognizes both strict ({{FLD_x}}) and hallucinated 
     ({FLD_x}) outputs, ensuring field integrity even when using smaller AI models.

   - RESILIENCE LAYER (THINKING-MODEL READY):
     * SANITIZATION FIREWALL: Automatically strips conversational "chatter" and internal 
       reasoning blocks (<think> tags) generated by thinking models like gpt-oss.
     * PERSISTENT CLIENT: Uses a dedicated Ollama Client with a 180-second timeout to 
       accommodate the deep reasoning phases of complex technical models.
     * REFLEXION & PANIC MODE: Dual-layer validation checks for language accuracy, length 
       deviations, and prompt leaks, triggering an automatic "Panic Mode" non-JSON retry.
     * ATOMIC COMMIT REBUILD: Builds a paragraph "plan" before modification; if parsing fails, 
       it falls back to raw text insertion to prevent data loss or document corruption.

   - TERMINOLOGY LOCK & CONSULTANT AUDIT:
     Injects an Engineering Glossary into the primary prompt. Optionally engages a "Consultant 
     Mode" (Secondary Model) to perform a dedicated Terminology Audit of the translation.

2. RECOMMENDED TRANSLATION MODELS (Ollama)
   -------------------------------------------------------------------------------------------------
   - POWERHOUSE: GPT-OSS 20B (Recommended) - Superior semantic understanding for STEM/Engineering.
     > Command: ollama pull gpt-oss:20b
   - SPECIALIST: TranslateGemma 3 (27B) - Optimized for high-fidelity technical specs & formatting.
     > Command: ollama pull translategemma:27b
   - POLYGLOT: Qwen-MT (Qwen 3) - Gold standard for CJK (Chinese/Japanese/Korean) manuals.
     > Command: ollama pull qwen-mt
   - SPEEDSTER: Qwen 3 (4B) - Ultra-fast; designed for legacy hardware and 8GB RAM systems.
     > Command: ollama pull qwen3:4b
   - LOCALIZER: T&L Specialist (50B) - Specialized for cultural adaptation and EIA reports.
     > Command: ollama pull ALIENTELLIGENCE/translationandlocalizationspecialist

3. SECONDARY CONSULTANT MODELS (Terminology Audit)
   -------------------------------------------------------------------------------------------------
   Used in "Consultant Mode" to double-check technical nomenclature without translating.
   - Engineering Manuals: `ollama pull ALIENTELLIGENCE/engineeringtechnicalmanuals`
   - Structural Engineer: `ollama pull joreilly86/structural_llama_3.0`
   - Civil Structure V2:  `ollama pull ALIENTELLIGENCE/civilstructureengineerv2`
   - Mechanical V2:       `ollama pull ALIENTELLIGENCE/mechanicalengineer`
   - Electrical V2:       `ollama pull ALIENTELLIGENCE/electricalengineerv2`
   - Chemical Engineer:   `ollama pull ALIENTELLIGENCE/chemicalengineer`
   - Industrial Engineer: `ollama pull ALIENTELLIGENCE/industrialengineer`

4. OPERATIONAL WORKFLOW
   -------------------------------------------------------------------------------------------------
   1. Initialize: Run `python translator_gui.py`. Checks for Ollama availability automatically.
   2. Ingest: "Browse" to select single or multiple .docx files (Batch Support).
   3. Context Scan: System reads the doc to establish "Domain Context" (e.g., Civil vs Electrical).
   4. Execute: Processing runs on a background thread with real-time log updates.
   5. Verify: Output saved as `_translated.docx` with all colors, formatting, and fields preserved.
====================================================================================================
"""

import tkinter as tk
from tkinter import ttk, filedialog, messagebox, scrolledtext
import threading
import sys
import os
import time
import datetime
import re
import ollama
from ollama import Client
import subprocess
from docx import Document
from docx.shared import Pt, RGBColor
from docx.oxml.ns import qn  # Required for XML Field detection
from docx.oxml import OxmlElement
from docx.text.run import Run
from docx.text.paragraph import Paragraph 
from docx.oxml.text.paragraph import CT_P # Required for robust Text Box type checking
from copy import deepcopy
import html
import json
from langdetect import detect, LangDetectException

# ====================================================================================================
#   CLASS: TRANSLATION ENGINE
#   The backend logic. Runs on a background thread to keep the GUI responsive.
# ====================================================================================================

class TranslationEngine:
    """
    The engine encapsulates the specific 'Engineering Edition' logic for document reconstruction.
    It runs inside a separate thread to prevent the GUI from freezing.
    """
    def __init__(self, config, log_callback, progress_callback):
        self.config = config
        self.log = log_callback
        self.update_progress = progress_callback
        self.stop_flag = False

        # Initialize the persistent client with an extended timeout (180s)
        # to prevent crashes during long "Thinking" phases.
        self.client = Client(timeout=180.0)
        
        # --- ADAPTIVE CONTEXT WINDOW ---
        self.context_buffer = []      # Rolling buffer for immediate previous text
        self.fixed_context = ""       # Permanent Domain/Tone
        self.translation_history = [] # Kept for backward compatibility
        self.document_context = ""
        self.use_json_mode = False    # Will be checked in Pre-Flight
        
    def format_time(self, seconds):
        """Converts seconds into HH:MM:SS format for the log."""
        return str(datetime.timedelta(seconds=int(seconds)))

    def update_history(self, new_text):
        """
        Updates the Adaptive Context Window.
        - Maintains a rolling buffer of the last ~2000 characters.
        - The 'Fixed Context' (Domain/Tone) is stored separately in self.fixed_context
          and applied dynamically during prompt generation.
        """
        # 1. Strip tags/placeholders to keep context clean and dense
        clean_text = re.sub(r'\{.*?\}', '', new_text).strip()
        if not clean_text: return

        # 2. Add to rolling buffer
        self.context_buffer.append(clean_text)
        
        # 3. Prune old entries to keep window size optimal (approx 2000 chars)
        max_chars = 2000
        current_len = sum(len(t) for t in self.context_buffer)
        
        while current_len > max_chars and len(self.context_buffer) > 0:
            removed = self.context_buffer.pop(0) # Remove oldest sentence/paragraph
            current_len -= len(removed)

    # --- 1. REFLEXION LOGIC (STABLE CORE) ---
    def _reflexion_check_is_chatty(self, text):
        """
        Pure logic check. Returns True if text looks like conversational filler.
        """
        # 1. Regex for obvious filler
        lazy_triggers = [
            r"^(Here|Sure|Note|Okay|Apologies|I have|The translation|Below is)", 
            r"(translation is|following is)[:\.]?$",
            r"^[\"']?Translation[:\s]",
            r"^[\"']?Translated text[:\s]",
            r"I cannot translate",
            r"As an AI"
        ]
        for trigger in lazy_triggers:
            if re.search(trigger, text, re.IGNORECASE):
                return True

        # 2. Length Ratio Heuristic (Hallucination check)
        # If output is > 3x input length, it's likely a rant/explanation, not a translation.
        
        # 3. Colon Heuristic
        # Engineering text rarely starts with "Word: ..." unless it's a definition.
        # Chatty models often do "Portuguese: [Text]"
        if re.match(r'^[A-Za-z]+:', text) and len(text.split()) > 5:
            return True

        return False

    # --- 2. SANITIZATION FIREWALL (ENGINEERING GRADE) ---
    def _sanitize_output(self, text):
        """
        Aggressive post-processing to remove conversational filler, 
        fix encoding errors, strip HTML entities, repair malformed tags,
        and eliminate 'hanging backslash' syntax errors.
        
        Uses a Whitelist to protect Engineering Tags ({b}, {c:HEX}, {FLD_x})
        while stripping hallucinated tags (e.g. {user}, {translation}).
        """
        if not text: return ""

        # 1. Strip "Thinking" blocks (For GPT-OSS, DeepSeek R1 / Reasoning Models)
        text = re.sub(r'<(think|reasoning|scratchpad|chain_of_thought)>.*?</\1>', '', text, flags=re.DOTALL | re.IGNORECASE).strip()

        # 2. Decode HTML Entities & Unicode
        text = html.unescape(text)
        try:
            # Fix double-encoded unicode (e.g. "\\u00e9" -> "é")
            if "\\u" in text:
                text = text.encode('utf-8').decode('unicode_escape')
            # Fix raw byte artifacts (e.g. "\\xC3\\xA9")
            if "\\x" in text:
                text = text.encode('latin1').decode('utf-8')
        except:
            pass

        # 3. Strip Markdown & JSON Artifacts
        if '```' in text:
            text = re.sub(r'```(?:json)?', '', text)
        
        # Remove JSON wrapper syntax if the regex caught edges
        text = re.sub(r'^\s*\{\s*"t"\s*:\s*', '', text)  # Starts with {"t":
        text = re.sub(r'^\s*"\s*', '', text)              # Starts with "
        text = re.sub(r'\s*"\s*\}\s*$', '', text)         # Ends with "}

        # 4. Fix Hanging Backslashes & Escaped Quotes
        text = text.strip()
        if text.endswith('\\"'):
            text = text[:-2] 
        elif text.endswith('\\'):
            text = text.rstrip('\\')
        if text.startswith('\\"'):
            text = text[2:]

        # 5. Repair Malformed Tags (Fuzzy Logic)
        text = re.sub(r'\{\s*["\\]+([a-z]+)\s*\}', r'{\1}', text)      # Fix {"b} -> {b}
        text = re.sub(r'\{\s*/\s*["\\]+([a-z]+)\s*\}', r'{/\1}', text) # Fix {/b"} -> {/b}
        text = re.sub(r'\{\s*([a-z]+)\s*\}', r'{\1}', text)            # Fix { b } -> {b}
        text = re.sub(r'\{\{([a-z]+)\}\}', r'{\1}', text)              # Fix {{b}} -> {b}
        
        # Fix malformed Color Tags (e.g. {c: FFFF } -> {c:FFFF})
        text = re.sub(r'\{\s*c\s*:\s*([0-9A-Fa-f]+)\s*\}', r'{c:\1}', text)

        # 6. Strip HTML-style Hallucinations
        text = re.sub(r'<br\s*/?>', ' ', text, flags=re.IGNORECASE)
        text = re.sub(r'<[^>]+>', '', text) 

        # 7. Remove Conversational Filler (The "Firewall")
        start_leaks = [
            r'^The following table[:\.]?', 
            r'^Here is the translation[:\.]?',
            r'^Here are a few options[:\.]?',
            r'^Note[:\.]',
            r'^Translation[:\.]',
            r'^Translated text[:\.]',
            r'^Sure, here is[:\.]?',
            r'^This appears to be[:\.]?',
            r'^I have translated[:\.]?',
            r'^In this context[:\.]?',
            r'^Output[:\.]?'
        ]
        for pattern in start_leaks:
            text = re.sub(pattern, '', text, flags=re.IGNORECASE | re.MULTILINE).strip()

        # 8. WHITELIST PROTECTION (Case-Insensitivity)
        valid_tags = [
            "b", "i", "u", "sup", "sub", "br", "tab", "c", "link",
            "/b", "/i", "/u", "/sup", "/sub", "/c", "/link"
        ]
        
        def filter_tags(match):
            full_tag = match.group(0) # e.g. "{B}" or "{C:FF0000}"
            # Extract the core tag name (e.g. "C" from "{C:FF0000}")
            inner_content = match.group(1).lower() # Force Lowercase for check
            
            # Always allow Field tags ({{FLD_x}}) and Color tags (case-insensitive check)
            if "fld_" in full_tag.lower() or inner_content in valid_tags:
                return full_tag
            
            # If it's an unknown tag, delete it
            return " "

        # Regex captures {tagname...} 
        text = re.sub(r'\{/?([a-zA-Z0-9]+)(?::[^}]+)?\}', filter_tags, text)

        # 9. Cleanup & Whitespace
        text = text.replace('**', '').replace('__', '')
        
        import unicodedata
        text = "".join(ch for ch in text if unicodedata.category(ch)[0] != "C" or ch in ['\n', '\t'])
        text = re.sub(r'\s+', ' ', text).strip()

        return text

    def _is_leak_detected(self, text, system_prompt_snippet=""):
        """
        Robustly detects if the AI has outputted instructions, metadata, or refusals.
        Uses Regex for header detection to prevent false positives on 
        valid engineering terms like 'Source' or 'Target'.
        """
        text_clean = text.strip().lower()
        
        # 1. HARD TRIGGERS: Phrases that NEVER belong in a translation
        # (Includes specific System Prompt keywords + Common AI Refusals)
        hard_triggers = [
            # Your System Prompt Leaks
            "you are a specialized", "tag architecture", "technical constancy",
            "zero hallucination", "translate the input text", "standard & reference lock",
            "output only the translated", "context (previous text)", "strict rules",
            "maintain brevity", 
            # AI Refusals/Boilerplate
            "as an ai", "i cannot translate", "i apologize", "i am unable to",
            "large language model", "cannot fulfill", "content policy"
        ]
        
        if any(trigger in text_clean for trigger in hard_triggers):
            return True

        # 2. SOFT TRIGGERS (REGEX): Only count if they look like Headers/Metadata
        # This fixes the bug where "Connect the power source." was flagged as a leak.
        # Matches only: "Source: ...", "Translation: ...", "Note: ..." at start of lines.
        header_patterns = [
            r'^(source|target|input|output|language)\s*:\s*', 
            r'^(translation|translated text|here is|sure)\s*[:\.,]',
            r'^note\s*:',
            r'^comments?\s*:',
        ]
        
        for pattern in header_patterns:
            if re.search(pattern, text_clean, re.MULTILINE):
                return True

        # 3. PROMPT ECHO CHECK (Fuzzy Match)
        if len(text) > 30 and system_prompt_snippet:
            # Check if the distinctive start of your system prompt appears in the output
            # (Normalizing spaces prevents formatting misses)
            snippet_sig = " ".join(system_prompt_snippet.split()[:10]).lower()
            text_sig = " ".join(text.split()).lower()
            if snippet_sig in text_sig:
                return True

        return False

    # --- 3. XML FIELD & FONT DNA ENGINE (ADVANCED) ---

    def get_dominant_font_properties(self, paragraph):
        """
        Scans the paragraph runs to find the most common font settings.
        Do NOT capture bold/italic/underline/sub/sup as 'dominant' to avoid
        infecting the whole paragraph if the first word matches these styles.
        Only capture Font Name, Size, and Color.
        """
        if not paragraph.runs: return None
        for run in paragraph.runs:
            if run.text.strip():
                return {
                    'name': run.font.name,
                    'size': run.font.size,
                    'color': run.font.color.rgb if run.font.color else None,
                    'highlight': run.font.highlight_color,
                    # Explicitly omit formatting toggles from the "Default" set
                    'bold': False,
                    'italic': False
                }
        return None

    def apply_font_properties(self, run, font_props):
        """Applies stored font settings to a new run."""
        if not font_props: return
        if font_props.get('name'): run.font.name = font_props['name']
        if font_props.get('size'): run.font.size = font_props['size']
        if font_props.get('color'): run.font.color.rgb = font_props['color']
        if font_props.get('highlight'): run.font.highlight_color = font_props['highlight']

    def robust_xml_copy(self, element):
        """
        Creates a deep copy of an lxml element.
        Standard deepcopy is fully compatible with lxml elements and 
        automatically preserves the namespace map (nsmap) and attributes.
        """
        return deepcopy(element)
        
    def _optimize_tags(self, text):
        """
        Merges adjacent identical formatting tags to clean up 'dirty' document structures.
        Fixes split words in tables (e.g. {b}Sobreelev{/b}{b}.{/b} -> {b}Sobreelev.{/b}).
        """
        # Regex finds: {tag}TEXT{/tag}{tag}MORE{/tag}
        pattern = r'\{([a-z]+(?::[0-9A-F]+)?)\}(.*?)\{/\1\}\{\1\}(.*?)\{/\1\}'
        while True:
            # Recursively merge adjacent identical tags
            new_text = re.sub(pattern, r'{\1}\2\3{/\1}', text, flags=re.IGNORECASE)
            if new_text == text: 
                break
            text = new_text
        return text

    def extract_text_and_fields(self, paragraph):
        """
        Recursively extracts text and locks complex fields to prevent corruption.
        Strictly locks legacy fields (SEQ, REF, PAGEREF, TOC) to prevent 
        index corruption and allow F9 updates.
        """
        text_builder = ""
        fields = []
        
        def process_element(element, current_fields):
            nonlocal text_builder
            for child in element:
                tag_name = child.tag.rsplit('}', 1)[-1]
                
                # --- 1. COMPLEX FIELDS (Date Pickers, Dropdowns) ---
                if tag_name == 'sdt':
                    sdt_pr = child.find('.//w:sdtPr', namespaces=child.nsmap)
                    is_complex = False
                    if sdt_pr is not None:
                        # Detect Date or Dropdown controls
                        if (sdt_pr.find('.//w:date', namespaces=child.nsmap) is not None or
                            sdt_pr.find('.//w:dropDownList', namespaces=child.nsmap) is not None or
                            sdt_pr.find('.//w:comboBox', namespaces=child.nsmap) is not None):
                            is_complex = True
                    
                    if is_complex:
                        # Treat as immutable field to preserve interactivity
                        current_fields.append([self.robust_xml_copy(child)])
                        text_builder += f"{{{{FLD_{len(current_fields)-1}}}}}"
                        continue
                    else:
                        # Just a text container -> recurse
                        sdt_content = child.find('.//w:sdtContent', namespaces=child.nsmap)
                        if sdt_content is not None:
                            process_element(sdt_content, current_fields)
                    continue

                # --- 2. HYPERLINKS ---
                if tag_name == 'hyperlink':
                    r_id = child.get(qn('r:id')) or ""
                    text_builder += f"{{link:{r_id}}}" 
                    process_element(child, current_fields)
                    text_builder += "{/link}"
                    continue
                
                # --- 3. ATOMIC FIELDS ---
                if tag_name == 'fldSimple':
                    current_fields.append([self.robust_xml_copy(child)])
                    text_builder += f"{{{{FLD_{len(current_fields)-1}}}}}"
                    continue
                
                if tag_name == 'smartTag':
                    process_element(child, current_fields)
                    continue

                # --- 4. TEXT RUNS ---
                if tag_name == 'r':
                    # Detect Legacy Fields (SEQ, REF, PAGEREF, TOC)
                    # If a run contains ANY field instructions, treat the whole run as a locked token.
                    if (child.findall('.//w:fldChar', namespaces=child.nsmap) or 
                        child.findall('.//w:instrText', namespaces=child.nsmap)):
                        current_fields.append([self.robust_xml_copy(child)])
                        text_builder += f"{{{{FLD_{len(current_fields)-1}}}}}"
                        continue

                    run_wrapper = Run(child, paragraph)
                    text = run_wrapper.text
                    
                    if not text:
                        if child.findall('.//w:br', namespaces=child.nsmap): text = "{br}"
                        elif child.findall('.//w:tab', namespaces=child.nsmap): text = "{tab}"
                        elif child.findall('.//w:cr', namespaces=child.nsmap): text = "{br}"
                        else: continue
                    else:
                        # Escape brackets to prevent tag confusion
                        text = text.replace("{", "(").replace("}", ")")

                    # Extract Visual DNA
                    prefix, suffix = "", ""
                    if run_wrapper.bold: prefix += "{b}"; suffix = "{/b}" + suffix
                    if run_wrapper.italic: prefix += "{i}"; suffix = "{/i}" + suffix
                    if run_wrapper.underline: prefix += "{u}"; suffix = "{/u}" + suffix
                    if run_wrapper.font.superscript: prefix += "{sup}"; suffix = "{/sup}" + suffix
                    if run_wrapper.font.subscript: prefix += "{sub}"; suffix = "{/sub}" + suffix
                    if run_wrapper.font.color and run_wrapper.font.color.rgb:
                        prefix += f"{{c:{run_wrapper.font.color.rgb}}}"
                        suffix = "{/c}" + suffix
                    
                    text_builder += f"{prefix}{text}{suffix}"

        process_element(paragraph._element, fields)
        
        # Optimize to fix broken words (e.g. {b}H{/b}{b}ello{/b} -> {b}Hello{/b})
        if text_builder: 
            text_builder = self._optimize_tags(text_builder)
            
        return text_builder, fields

    def rebuild_paragraph(self, paragraph, translated_text, font_props, original_format, fields):
        """
        Reconstructs the paragraph with Atomic Commit.
        Removes manual 'numPr' injection to prevent index corruption. 
        Relies on Paragraph Style for automatic numbering (Updated via F9).
        """
        # 1. Tag Healing
        translated_text = re.sub(r'\{\s*/\s*([a-z]+)\s*\}', r'{/\1}', translated_text, flags=re.IGNORECASE)
        translated_text = re.sub(r'\{\s*([a-z]+)\s*\}', r'{\1}', translated_text, flags=re.IGNORECASE)
        for tag in ['b', 'i', 'u', 'sup', 'sub']:
            open_count = len(re.findall(f'{{{tag}}}', translated_text, re.IGNORECASE))
            close_count = len(re.findall(f'{{/{tag}}}', translated_text, re.IGNORECASE))
            if open_count > close_count: 
                translated_text += f"{{/{tag}}}" * (open_count - close_count)

        # 2. Build Plan
        build_plan = []
        state = {'bold': False, 'italic': False, 'underline': False, 'sup': False, 'sub': False, 'color': None, 'is_link': False, 'link_id': None}
        
        try:
            token_pattern = r'(\{\{?FLD_\d+\}?\}|\{(?:br|tab|b|i|u|sup|sub|link(?::\w+)?|c:[0-9A-Fa-f]+|/b|/i|/u|/sup|/sub|/link|/c)\})'
            tokens = re.split(token_pattern, translated_text, flags=re.IGNORECASE)

            for token in tokens:
                if not token: continue
                low_token = token.lower()

                if low_token == "{b}": state['bold'] = True; continue
                if low_token == "{/b}": state['bold'] = False; continue
                if low_token == "{i}": state['italic'] = True; continue
                if low_token == "{/i}": state['italic'] = False; continue
                if low_token == "{u}": state['underline'] = True; continue
                if low_token == "{/u}": state['underline'] = False; continue
                if low_token == "{sup}": state['sup'] = True; continue
                if low_token == "{/sup}": state['sup'] = False; continue
                if low_token == "{sub}": state['sub'] = True; continue
                if low_token == "{/sub}": state['sub'] = False; continue
                
                if low_token.startswith("{link"):
                    state['is_link'] = True
                    state['link_id'] = token.split(":")[1].replace("}", "") if ":" in token else None
                    continue
                if low_token == "{/link}": state['is_link'] = False; state['link_id'] = None; continue

                if low_token.startswith("{c:"):
                    try:
                        hex_code = low_token[3:-1].upper()
                        if len(hex_code) == 6:
                            state['color'] = RGBColor(int(hex_code[:2], 16), int(hex_code[2:4], 16), int(hex_code[4:], 16))
                    except: pass
                    continue
                if low_token == "{/c}": state['color'] = None; continue

                if low_token == "{br}": build_plan.append(('break', None, None)); continue
                if low_token == "{tab}": build_plan.append(('tab', None, None)); continue

                if "FLD_" in token:
                    match = re.search(r'FLD_\s*(\d+)', token)
                    if match and 0 <= int(match.group(1)) < len(fields):
                        # Use state.copy() to protect shared state objects
                        build_plan.append(('field', fields[int(match.group(1))], state.copy()))
                    else:
                        build_plan.append(('text', token, state.copy()))
                    continue

                build_plan.append(('text', token, state.copy()))

        except Exception as e:
            self.log(f"[WARN] Rebuild parsing failed ({e}). Fallback to raw text.")
            # FALLBACK: Just set text if parsing fails, but clear safely
            p_element = paragraph._element
            for child in list(p_element):
                if child.tag.endswith('}r') or child.tag.endswith('}hyperlink'):
                    p_element.remove(child)
            paragraph.add_run(translated_text)
            return

        # 3. Execute Plan
        # Capture Format
        p_style = paragraph.style
        p_alignment = paragraph.alignment
        p_fmt = paragraph.paragraph_format
        p_left, p_right = p_fmt.left_indent, p_fmt.right_indent
        p_first = p_fmt.first_line_indent
        p_before, p_after = p_fmt.space_before, p_fmt.space_after
        p_tab_stops = [(ts.position, ts.alignment, ts.leader) for ts in p_fmt.tab_stops]

        p_element = paragraph._element
        for child in list(p_element):
            # Remove runs (r) and hyperlinks, preserve pPr (properties)
            if child.tag.endswith('}r') or child.tag.endswith('}hyperlink'):
                p_element.remove(child)

        # Restore Props
        try:
            if p_style: paragraph.style = p_style 
            paragraph.alignment = p_alignment
            paragraph.paragraph_format.left_indent = p_left
            paragraph.paragraph_format.right_indent = p_right
            paragraph.paragraph_format.first_line_indent = p_first
            paragraph.paragraph_format.space_before = p_before
            paragraph.paragraph_format.space_after = p_after
            for ts in p_tab_stops: paragraph.paragraph_format.tab_stops.add_tab_stop(*ts)
            
            # NOTE: We deliberately do NOT restore pPr.numPr here.
            # Letting the 'paragraph.style' dictate numbering prevents XML corruption.

        except Exception as e:
            self.log(f"[WARN] Format restoration partial fail: {e}")

        # Rebuild Content
        current_hyperlink = None
        for action_type, content, item_state in build_plan:
            if item_state and item_state['is_link'] and item_state['link_id']:
                if current_hyperlink is None or current_hyperlink.get(qn('r:id')) != item_state['link_id']:
                    current_hyperlink = OxmlElement('w:hyperlink')
                    current_hyperlink.set(qn('r:id'), item_state['link_id'])
                    paragraph._p.append(current_hyperlink)
            else:
                current_hyperlink = None

            if action_type == 'break': paragraph.add_run().add_break()
            elif action_type == 'tab': paragraph.add_run().add_tab()
            elif action_type == 'field':
                target = current_hyperlink if current_hyperlink is not None else paragraph._p
                for xml_elem in content: target.append(xml_elem)
            elif action_type == 'text':
                if current_hyperlink is not None:
                    run = Run(OxmlElement('w:r'), paragraph)
                    current_hyperlink.append(run._element)
                else:
                    run = paragraph.add_run()
                
                run.text = content
                if font_props: self.apply_font_properties(run, font_props)
                if item_state['bold']: run.bold = True
                if item_state['italic']: run.italic = True
                if item_state['underline']: run.underline = True
                if item_state['sup']: run.font.superscript = True
                if item_state['sub']: run.font.subscript = True
                if item_state['color']: run.font.color.rgb = item_state['color']
                if item_state['is_link']:
                    run.font.color.rgb = RGBColor(0, 0, 255)
                    run.font.underline = True

    def set_updatefields_true(self, doc):
        """
        Injects the <w:updateFields w:val="true"/> setting into the docx.
        Refactored to take the DOC object directly to avoid re-opening file.
        """
        try:
            settings = doc.settings.element
            update_fields = settings.find(qn('w:updateFields'))
            
            if update_fields is None:
                update_fields = OxmlElement('w:updateFields')
                settings.append(update_fields)
            
            update_fields.set(qn('w:val'), 'true')
        except Exception as e:
            self.log(f"[WARN] Failed to set auto-update fields: {e}")

    def consult_expert_on_terminology(self, original_text, translated_text):
        """
        Consultant Mode (Secondary Model).
        Corrects terminology while strictly preserving tags.
        """
        if not self.config['model_secondary'] or self.config['model_secondary'] == "None":
            return translated_text
        if len(translated_text.strip()) < 5: 
            return translated_text

        input_tags = re.findall(r'(\{[^{}]+\})', translated_text)
        
        system_prompt = f"""SYSTEM: ENGINEERING_QA_AUDITOR
TASK: Review DRAFT translation against SOURCE. Fix ONLY terminology errors.
SOURCE_LANG: {self.config['lang_in']}
TARGET_LANG: {self.config['lang_out']}
CRITICAL:
1. OUTPUT JSON: {{ "status": "FIX", "corrected": "STRING" }} or {{ "status": "PASS" }}
2. TAG INVARIANCE: PRESERVE ALL TAGS (e.g. {{b}}, {{FLD_1}}) EXACTLY.
"""
        try:
            token_budget = len(translated_text) * 2 + 150
            response = self.client.chat(model=self.config['model_secondary'], messages=[
                {'role': 'system', 'content': system_prompt},
                {'role': 'user', 'content': f"SOURCE: \"{original_text}\"\nDRAFT: \"{translated_text}\""}
            ], options={'temperature': 0.0, 'num_predict': token_budget})

            clean_json = response['message']['content'].strip()
            if "```" in clean_json: 
                clean_json = clean_json.split("```json")[-1].split("```")[0].strip()
            
            json_match = re.search(r'(\{.*\})', clean_json, re.DOTALL)
            if json_match: clean_json = json_match.group(1)

            data = json.loads(clean_json)

            if data.get("status") == "FIX" and "corrected" in data:
                fixed_text = data["corrected"]
                
                # Validation: Tag Integrity & Length
                output_tags = re.findall(r'(\{[^{}]+\})', fixed_text)
                if sorted(input_tags) != sorted(output_tags):
                    return translated_text # Reject: Tags broken
                
                if abs(len(fixed_text) - len(translated_text)) > max(20, len(translated_text) * 0.6):
                     return translated_text # Reject: Hallucination

                return fixed_text

        except Exception:
            pass
        return translated_text

    def translate_block_with_fidelity(self, paragraph, is_table_cell=False, is_table_header=False):
        """
        Main Translation Routine.
        Includes: Field Extraction -> Adaptive Context -> Panic Mode -> Atomic Rebuild.
        """
        if self.stop_flag: return False
        
        t0 = time.time()
        font_props = self.get_dominant_font_properties(paragraph)
        original_format = paragraph.paragraph_format
        
        tagged_source, preserved_fields = self.extract_text_and_fields(paragraph)
        clean_text = re.sub(r'\{.*?\}', '', tagged_source).strip()
        
        # 1. Skip empty text
        if not clean_text: return False
        
        # 2. Skip pure numbers/symbols (e.g. "100", "+/-")
        if re.match(r'^[\d.,+\-%/() \u2013\u2014-]+$', clean_text): return False 

        # 3. Skip short abbreviations in tables
        # Logic: If inside a table + 3 chars or less + Uppercase + Letters only -> Skip
        if is_table_cell and len(clean_text) <= 3 and clean_text.isupper() and clean_text.isalpha():
            return False
        
        rolling_ctx = "\n".join(getattr(self, 'context_buffer', []))
        fixed_ctx = getattr(self, 'fixed_context', "")
        context_str = f"{fixed_ctx}\n\nPREVIOUS TEXT:\n{rolling_ctx}" if fixed_ctx else f"PREVIOUS TEXT:\n{rolling_ctx}"

        is_drawing_list = re.match(r'^\s*[\d.]+[A-Z]+\.[\d]+', clean_text)
        word_count = len(clean_text.split())
        is_header = (clean_text.isupper() and word_count < 12) or (clean_text.istitle() and word_count < 4)
        
        special_instruction = ""
        if is_table_cell or is_table_header or is_drawing_list:
            special_instruction = """
            - RULE: PRESERVE LEADERS: If text starts with a code (e.g. "100.1.OMP.001"), KEEP IT EXACTLY at the start.
            - RULE: FORCE TRANSLATION of descriptors (Planta->Plan, Alçados->Elevations).
            - RULE: MERGE TAGS: Read through formatting tags to translate the whole word (e.g., {b}Preia{/b}{b}-Mar{/b}).
            """
        elif is_header:
            special_instruction = "- RULE: This is a DOCUMENT TITLE. Use formal, authoritative tone."

        use_json = getattr(self, 'use_json_mode', False)
        global_context_prompt = f"DOCUMENT CONTEXT: {self.document_context}" if self.document_context else ""

        if use_json:
            system_prompt = f"""SYSTEM: ENGINEER_DIGITAL_TWIN (JSON)
SOURCE: {self.config['lang_in']} | TARGET: {self.config['lang_out']}
{global_context_prompt}
FORMAT: {{"t": "TRANSLATED_TEXT"}}
CRITICAL: 1. Escape double quotes. 2. Keep tags {{b}}, {{i}}, {{c:HEX}}, {{FLD_x}} exactly.
3. NO CHATTER. 4. NO REFUSALS on property/legal text.
{special_instruction}
CONTEXT: {context_str}"""
        else:
            system_prompt = f"""SYSTEM: TECHNICAL_TRANSLATOR (DIRECT TEXT)
Translate {self.config['lang_in']} to {self.config['lang_out']}.
{global_context_prompt}
STRICT: Output ONLY translation. Keep all tags. Do not translate codes/numbers.
{special_instruction}
CONTEXT: {context_str}"""

        preview_in = (clean_text[:70] + '..') if len(clean_text) > 70 else clean_text
        self.log(f"┌── [SRC] \"{preview_in}\"")

        try:
            token_budget = max(1000, int(len(clean_text) * 6) + 500)
            fmt_arg = 'json' if use_json else None
            raw_output = ""

            for attempt in range(2):
                if self.stop_flag: return False
                try:
                    stream = self.client.chat(
                        model=self.config['model_primary'], 
                        messages=[{'role': 'system', 'content': system_prompt}, {'role': 'user', 'content': f"\"{tagged_source}\""}], 
                        format=fmt_arg, 
                        options={'temperature': 0.0, 'num_predict': token_budget},
                        stream=True
                    )
                    full_text = ""
                    for chunk in stream:
                        if self.stop_flag: return False
                        full_text += chunk.get('message', {}).get('content', '')
                    raw_output = full_text.strip()
                    if raw_output: break
                except Exception as e:
                    self.log(f"├── [RETRY] Communication error: {str(e)}")
                    time.sleep(1)

            sanitized_check = self._sanitize_output(raw_output)
            if not raw_output or len(sanitized_check) < 1:
                self.log("├── [WARN] Model failed to produce text. Engaging Zero-Reasoning Panic Mode...")
                panic_resp = self.client.chat(
                    model=self.config['model_primary'], 
                    messages=[{'role': 'user', 'content': f"Translate from {self.config['lang_in']} to {self.config['lang_out']} now. Output ONLY the translation. Keep tags: {tagged_source}"}], 
                    options={'temperature': 0.0, 'num_predict': 800} 
                )
                raw_output = panic_resp['message']['content'].strip()
                raw_output = re.sub(r'<think>.*?</think>', '', raw_output, flags=re.DOTALL).strip()

            result = raw_output
            parse_success = False

            if use_json:
                try:
                    if "```json" in raw_output:
                        clean_json = raw_output.split("```json")[-1].split("```")[0].strip()
                    else:
                        clean_json = raw_output.strip()
                    json_match = re.search(r'(\{|\[).*(\}|\])', clean_json, re.DOTALL)
                    if json_match: clean_json = json_match.group(0)

                    data = json.loads(clean_json)
                    if isinstance(data, dict) and "t" in data:
                        result = data["t"]
                        parse_success = True
                    elif isinstance(data, list) and len(data) > 0:
                        if isinstance(data[0], dict) and "t" in data[0]:
                            result = data[0]["t"]
                            parse_success = True
                        elif isinstance(data[0], str):
                            result = data[0]
                            parse_success = True
                except: pass
                
                if not parse_success:
                    match = re.search(r'"t"\s*:\s*"((?:[^"\\]|\\.)*)"', raw_output, re.DOTALL)
                    if match: 
                        result = match.group(1).replace('\\"', '"').replace('\\\\', '\\')
                        parse_success = True

            result = self._sanitize_output(result)
            
            # Validation Panic Mode
            is_too_long = len(result) > (len(tagged_source) * 2.0) + 50
            is_chatty = False
            if not parse_success or is_too_long:
                 is_chatty = self._reflexion_check_is_chatty(result)
            
            if is_too_long or is_chatty:
                self.log(f"├── [WARN] Output suspect (Len:{is_too_long} Chat:{is_chatty}). Retrying raw...")
                retry_response = self.client.chat(model=self.config['model_primary'], messages=[
                    {'role': 'system', 'content': f"Translate from {self.config['lang_in']} to {self.config['lang_out']}. Output ONLY the translation."},
                    {'role': 'user', 'content': tagged_source}
                ], options={'temperature': 0.0, 'num_predict': token_budget})
                result = retry_response['message']['content'].strip()
                if result.startswith('"') and result.endswith('"'): result = result[1:-1]
                result = self._sanitize_output(result)

            # Consultant Check
            if len(clean_text.split()) > 5 and self.config['model_secondary'] != "None":
                consultant_result = self.consult_expert_on_terminology(clean_text, result)
                if consultant_result != result:
                    self.log(f"├── [CONSULTANT] Refined: \"{consultant_result[:40]}...\"")
                    result = consultant_result

            self.rebuild_paragraph(paragraph, result, font_props, original_format, preserved_fields)
            self.update_history(re.sub(r'\{.*?\}', '', result))
            
            elapsed = time.time() - t0
            preview_out = (result[:70] + '..') if len(result) > 70 else result
            self.log(f"└── [TRG] \"{preview_out}\"   [{elapsed:.2f}s]")
            return True

        except Exception as e:
            self.log(f"└── [ERROR] Block Failed: {str(e)}. Keeping original text.")
            return False

    def perform_pre_flight_check(self):
        """
        Robustly checks if the model can output JSON. 
        Handles 'chatty' models like gpt-oss.
        """
        self.log(f"-> [SYSTEM] Running Pre-Flight Capability Check on '{self.config['model_primary']}'...")
        
        # Simplified prompt to reduce model confusion
        test_prompt = """SYSTEM: JSON_COMPILER
TASK: Convert INPUT to JSON.
FORMAT: {"t": "TEXT"}
INPUT: Hello"""

        try:
            response = self.client.chat(model=self.config['model_primary'], messages=[
                {'role': 'system', 'content': test_prompt},
                {'role': 'user', 'content': "Convert 'Hello' to JSON."}
            ], options={'temperature': 0.0, 'num_predict': 100})
            
            raw = response['message']['content'].strip()
            
            # 1. Clean Markdown (Standard gpt-oss behavior)
            if "```" in raw:
                # Split by code block markers and take the content inside
                raw = raw.split("```json")[-1].split("```")[0].strip()

            # 2. Extract JSON payload (Non-greedy regex is safer here)
            # Looks for the first occurrence of {"t": ...}
            json_match = re.search(r'\{\s*"t"\s*:.*?\DICTIONARY_END|\{.*?\}', raw, re.DOTALL)
            
            potential_json = raw
            if json_match:
                potential_json = json_match.group(0)

            # 3. Validation
            try:
                data = json.loads(potential_json)
                # Check if it has the key 't' (or is a valid list wrapper)
                if (isinstance(data, dict) and "t" in data):
                    self.log(f"-> [PASS] Model '{self.config['model_primary']}' supports JSON. Engaging Compiler Mode.")
                    return True
            except json.JSONDecodeError:
                pass
            
            self.log(f"-> [WARN] Model failed JSON test. Output: {raw[:40]}... (Switching to Text Mode)")
            return False
            
        except Exception as e:
            self.log(f"-> [ERROR] Pre-Flight failed ({str(e)}). Defaulting to Direct Text Mode.")
            return False
			
    # --- 6. BATCH PROCESSING LOOP ---

    def run(self):
        input_files = self.config.get('file_paths', [])
        if not input_files and 'file_path' in self.config:
             input_files = [self.config['file_path']]

        if not input_files:
            self.log("[CRITICAL] No files provided.")
            return

        self.use_json_mode = self.perform_pre_flight_check()
        self.log(f"-> Batch Started: {len(input_files)} files queued.")
        if self.config['model_secondary'] and self.config['model_secondary'] != "None":
             self.log(f"-> Consultant Mode: ACTIVE ({self.config['model_secondary']})")

        # Global Context Scan
        self.log("-> Performing Smart Context Scan (reading first 1000 words)...")
        context_sample = ""
        try:
            if input_files:
                temp_doc = Document(input_files[0])
                for p in temp_doc.paragraphs[:20]: 
                    context_sample += p.text + " "
                
                if len(context_sample) > 100:
                    ctx_prompt = "Analyze this document snippet. Output a 1-sentence description of the DOMAIN (e.g. Civil Eng) and TONE (e.g. Formal)."
                    ctx_response = self.client.chat(model=self.config['model_primary'], messages=[
                        {'role': 'system', 'content': ctx_prompt},
                        {'role': 'user', 'content': context_sample[:2000]}
                    ], options={'num_predict': 50, 'temperature': 0.0})
                    self.document_context = ctx_response['message']['content'].strip()
                    self.fixed_context = f"DOMAIN: {self.document_context}" # Set fixed context for Adaptive Window
                    self.log(f"-> [CONTEXT ESTABLISHED] {self.document_context}")
        except Exception as e:
            self.log(f"[WARN] Context scan failed: {e}")

        # Global Pre-Scan
        self.log("-> Scanning all files to calculate total workload...")
        total_global_items = 0
        for idx, f_path in enumerate(input_files):
            if self.stop_flag: return
            try:
                temp_doc = Document(f_path)
                for section in temp_doc.sections:
                    for part in [section.header, section.footer]:
                        total_global_items += len(part.paragraphs)
                        for table in part.tables:
                            for row in table.rows:
                                for cell in row.cells:
                                    total_global_items += sum(1 for p in cell.paragraphs if p.text.strip())
                total_global_items += len(temp_doc.paragraphs)
                for table in temp_doc.tables:
                    for row in table.rows:
                        for cell in row.cells:
                            total_global_items += sum(1 for p in cell.paragraphs if p.text.strip())
                for txbx in temp_doc.element.iter(qn('w:txbxContent')):
                    for child in txbx.iter(qn('w:p')):
                        total_global_items += 1
            except Exception as e:
                self.log(f"[WARN] Skipping scan for {os.path.basename(f_path)}: {e}")

        self.log(f"-> Total Workload: {total_global_items} blocks across {len(input_files)} files.")

        # Processing Loop
        start_time_global = time.time()
        global_processed_count = 0

        for file_index, input_path in enumerate(input_files):
            if self.stop_flag: break
            
            filename_base = os.path.basename(input_path)
            path_parts = os.path.splitext(input_path)
            
            # DEFAULT: Try saving next to original
            output_dir = os.path.dirname(input_path)
            output_filename = f"{path_parts[0]}_translated{path_parts[1]}"
            
            # SAFETY CHECK: Is directory writable?
            if not os.access(output_dir, os.W_OK):
                # Fallback to local 'translated_docs' folder
                fallback_dir = os.path.join(os.getcwd(), "translated_docs")
                os.makedirs(fallback_dir, exist_ok=True)
                output_path = os.path.join(fallback_dir, f"TRANSLATED_{filename_base}")
                self.log(f"[WARN] Source folder read-only. Saving to: {output_path}")
            else:
                output_path = output_filename
            
            self.log(f"------------------------------------------------")
            self.log(f"-> PROCESSING FILE {file_index + 1}/{len(input_files)}: {filename_base}")
            
            try:
                doc = Document(input_path)
            except Exception as e:
                self.log(f"[ERROR] Failed to load {filename_base}: {e}")
                continue

            processed_parts = set()

            # Headers & Footers
            for section in doc.sections:
                for part in [section.header, section.footer]:
                    if part.part not in processed_parts:
                        processed_parts.add(part.part)
                        for para in part.paragraphs:
                            if self.stop_flag: break
                            global_processed_count += 1
                            # 1. Header/Footer Loop
                            self.update_progress(global_processed_count, total_global_items, f"[{file_index+1}/{len(input_files)}] Header/Footer...", start_time=start_time_global)
                            self.translate_block_with_fidelity(para)
                        for table in part.tables:
                            for row in table.rows:
                                for cell in row.cells:
                                    for para in cell.paragraphs:
                                        if not para.text.strip(): continue
                                        if self.stop_flag: break
                                        global_processed_count += 1
                                        # 2. Header/Footer Table Loop
                                        self.update_progress(global_processed_count, total_global_items, f"[{file_index+1}/{len(input_files)}] H/F Table...", start_time=start_time_global)
                                        self.translate_block_with_fidelity(para, is_table_cell=True)

            # Body Paragraphs
            for para in doc.paragraphs:
                if self.stop_flag: break
                global_processed_count += 1
                # 3. Body Paragraphs Loop
                self.update_progress(global_processed_count, total_global_items, f"[{file_index+1}/{len(input_files)}] Body...", start_time=start_time_global)
                self.translate_block_with_fidelity(para)

            # Body Tables
            for table in doc.tables:
                for r_idx, row in enumerate(table.rows):
                    is_header_row = (r_idx == 0)
                    for cell in row.cells:
                        for para in cell.paragraphs:
                            if not para.text.strip(): continue
                            if self.stop_flag: break
                            global_processed_count += 1
                            
                            self.update_progress(
                                global_processed_count, 
                                total_global_items, 
                                f"[{file_index+1}/{len(input_files)}] Tables...", 
                                start_time=start_time_global
                            )
                            
                            # Pass the new flag
                            self.translate_block_with_fidelity(
                                para, 
                                is_table_cell=True, 
                                is_table_header=is_header_row 
                            )
            
            # Text Boxes
            for txbx in doc.element.iter(qn('w:txbxContent')):
                for child in txbx.iter(qn('w:p')):
                    if self.stop_flag: break
                    
                    # Correct Parent Proxy for Text Box paragraphs to prevent crash
                    if isinstance(child, CT_P):
                        para = Paragraph(child, doc._body)
                    else:
                        continue # Skip if not a valid paragraph element
                        
                    if not para.text.strip(): continue
                    global_processed_count += 1
                    # 5. Text Boxes Loop
                    self.update_progress(global_processed_count, total_global_items, f"[{file_index+1}/{len(input_files)}] Text Boxes...", start_time=start_time_global)
                    self.translate_block_with_fidelity(para)

            if not self.stop_flag:
                # Inject 'Force Update' trigger BEFORE saving
                try:
                    self.set_updatefields_true(doc) 
                    self.log(f"-> [INFO] 'Update Fields' trigger injected.")
                except Exception as e:
                    self.log(f"[WARN] Could not set auto-update trigger: {e}")

                # RETRY LOGIC FOR SAVING
                save_attempts = 0
                max_save_retries = 3
                saved_successfully = False
                
                while save_attempts < max_save_retries and not saved_successfully:
                    try:
                        doc.save(output_path)
                        self.log(f"-> [SUCCESS] Saved: {os.path.basename(output_path)}")
                        saved_successfully = True
                    except PermissionError:
                        save_attempts += 1
                        self.log(f"[WARN] File locked! Close '{os.path.basename(output_path)}' immediately. Retrying in 3s... ({save_attempts}/{max_save_retries})")
                        time.sleep(3) # Wait for user to close file
                    except Exception as e:
                        self.log(f"[ERROR] Save failed: {e}")
                        break
						
                if not saved_successfully:
                    self.log(f"[CRITICAL] Could not save file. Translation lost for this file.")

        if not self.stop_flag:
            total_time = time.time() - start_time_global
            self.log(f"================================================")
            self.log(f"-> BATCH COMPLETE. Time: {self.format_time(total_time)}")
            self.update_progress(total_global_items, total_global_items, "Batch Done.", start_time=start_time_global)
        else:
            self.log("-> ABORTED BY USER.")


# ====================================================================================================
#   CLASS: TRANSLATOR APP (GUI)
# ====================================================================================================

class TranslatorApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Offline AI Translator - Engineering Edition")
        self.geometry("900x750")
        self.configure(bg="#2b2b2b")
        style = ttk.Style()
        style.theme_use('clam')
        
        self.bg_color = "#2b2b2b"
        self.fg_color = "#ffffff"
        self.accent_color = "#4a90e2"
        
        style.configure("TFrame", background=self.bg_color)
        style.configure("TLabel", background=self.bg_color, foreground=self.fg_color, font=("Segoe UI", 10))
        style.configure("Header.TLabel", font=("Segoe UI", 16, "bold"), foreground=self.accent_color)
        style.configure("TButton", background="#3c3c3c", foreground="white", borderwidth=0, focuscolor="none")
        style.map("TButton", background=[("active", self.accent_color)])
        style.configure("TProgressbar", troughcolor="#3c3c3c", background=self.accent_color, thickness=20)
        style.configure("TEntry", fieldbackground="#3c3c3c", foreground="white")
        style.configure("TLabelframe", background=self.bg_color, foreground=self.fg_color)
        style.configure("TLabelframe.Label", background=self.bg_color, foreground=self.accent_color, font=("Segoe UI", 10, "bold"))

        self.file_path = tk.StringVar()
        self.lang_in = tk.StringVar(value="Portuguese (Portugal)")
        self.lang_out = tk.StringVar(value="English (UK)")
        self.model_primary = tk.StringVar(value="") 
        self.model_secondary = tk.StringVar(value="None")
        self.temperature = tk.DoubleVar(value=0.0)
        self.progress_var = tk.DoubleVar(value=0)
        self.status_var = tk.StringVar(value="Idle - Ready to load document")
        self.engine = None
        self.worker_thread = None

        self.create_widgets()

    def get_installed_models(self):
        models = set()
        try:
            # Attempt to use the official Python library first
            response = ollama.list()
            if hasattr(response, 'models'):
                for m in response.models:
                    if hasattr(m, 'model'): models.add(m.model)
                    elif hasattr(m, 'name'): models.add(m.name)
            elif isinstance(response, dict) and 'models' in response:
                for m in response['models']:
                    models.add(m.get('model') or m.get('name'))
        except Exception as e:
            # Fallback if library fails (e.g. connection issue or old version)
            print(f"Ollama Library fetch failed: {e}")

        if not models:
            try:
                # Cross-platform StartupInfo (Windows Only)
                startup_info = None
                if os.name == 'nt':
                    startup_info = subprocess.STARTUPINFO()
                    startup_info.dwFlags |= subprocess.STARTF_USESHOWWINDOW
                
                # Run the CLI command with the correct startupinfo
                result = subprocess.run(
                    ['ollama', 'list'], 
                    capture_output=True, 
                    text=True, 
                    encoding='utf-8', 
                    errors='ignore',
                    startupinfo=startup_info 
                )
                
                if result.returncode == 0:
                    lines = result.stdout.strip().splitlines()
                    # Skip header line (NAME ID SIZE MODIFIED) and parse
                    for line in lines[1:]:
                        if line.strip():
                            parts = line.split()
                            if parts: models.add(parts[0])
            except Exception as e:
                print(f"CLI fetch failed: {e}")
                
        return sorted(list(models))

    def create_widgets(self):
        main_pad = 20
        header = ttk.Frame(self)
        header.pack(fill="x", padx=main_pad, pady=(20, 10))
        ttk.Label(header, text="AI DOCUMENT TRANSLATOR", style="Header.TLabel").pack(side="left")
        ttk.Label(header, text="  |  Engineering Documents", foreground="#888").pack(side="left", pady=(8,0))
  
        f_frame = ttk.LabelFrame(self, text="INPUT DOCUMENT(S) (.docx)", padding=15)
        f_frame.pack(fill="x", padx=main_pad, pady=5)
        
        self.entry_file = ttk.Entry(f_frame, textvariable=self.file_path, font=("Consolas", 10))
        self.entry_file.pack(side="left", fill="x", expand=True, padx=(0,10))
        
        # Clear "Browse" selection if user types manually
        self.entry_file.bind("<Key>", lambda e: setattr(self, 'selected_files', []))
        
        ttk.Button(f_frame, text="BROWSE...", command=self.browse_file, width=15).pack(side="right")

        c_frame = ttk.LabelFrame(self, text="CONFIGURATION", padding=15)
        c_frame.pack(fill="x", padx=main_pad, pady=5)
        
        language_options = [
            # Core & Regional Variants
            "Portuguese (Portugal)", "Portuguese (Brazil)", 
            "English (UK)", "English (US)",
            "Spanish (Spain)", "Spanish (Latin America)",
            "French (France)", "French (Canada)",
            
            # Major Global Markets
            "German", "Italian", "Chinese (Simplified)", "Chinese (Traditional)",
            "Japanese", "Korean", "Russian", "Arabic",
            
            # African
            "Cape Verdean", "Swahili", "Afrikaans", "Amharic", "Yoruba", "Zulu",
            
            # European (Western, Central & Eastern)
            "Dutch", "Polish", "Ukrainian", "Turkish", "Greek", 
            "Swedish", "Danish", "Norwegian", "Finnish", 
            "Czech", "Hungarian", "Romanian", "Bulgarian",
            "Slovak", "Croatian", "Serbian", "Slovenian",
            
            # Asian & Middle Eastern
            "Hindi", "Bengali", "Thai", "Vietnamese", "Indonesian", 
            "Malay", "Hebrew", "Persian (Farsi)", "Urdu", "Tagalog"
        ]
        # 1. Languages
        ttk.Label(c_frame, text="Source:").grid(row=0, column=0, sticky="w", padx=5)
        self.cbox_lang_in = ttk.Combobox(c_frame, textvariable=self.lang_in, values=language_options, width=28, state="readonly")
        self.cbox_lang_in.grid(row=0, column=1, padx=5)
        
        ttk.Label(c_frame, text="Target:").grid(row=0, column=2, sticky="w", padx=(20,5))
        self.cbox_lang_out = ttk.Combobox(c_frame, textvariable=self.lang_out, values=language_options, width=28, state="readonly")
        self.cbox_lang_out.grid(row=0, column=3, padx=5)
        
        # 2. Models
        available_models = self.get_installed_models()
        if self.model_primary.get() not in available_models:
            if any("gpt-oss" in m for m in available_models):
                self.model_primary.set(next((m for m in available_models if "gpt-oss" in m), ""))
            elif any("translategemma" in m for m in available_models):
                self.model_primary.set(next((m for m in available_models if "translategemma" in m), ""))
            elif available_models:
                self.model_primary.set(available_models[0])
            else:
                self.model_primary.set("None")

        ttk.Label(c_frame, text="Primary Model:").grid(row=1, column=0, sticky="w", padx=5, pady=10)
        
        self.cbox_primary = ttk.Combobox(c_frame, textvariable=self.model_primary, width=45, state="readonly")
        self.cbox_primary['values'] = ["Loading..."] 
        self.cbox_primary.set("Loading...")
        self.cbox_primary.grid(row=1, column=1, padx=5)
        
        ttk.Label(c_frame, text="Consultant:").grid(row=1, column=2, sticky="w", padx=(20,5))
        
        self.cbox_secondary = ttk.Combobox(c_frame, textvariable=self.model_secondary, width=45, state="readonly")
        self.cbox_secondary['values'] = ["Loading..."]
        self.cbox_secondary.set("Loading...")
        self.cbox_secondary.grid(row=1, column=3, padx=5)

        ttk.Label(c_frame, text="Temp:").grid(row=2, column=0, sticky="w", padx=5)
        self.temp_display = tk.StringVar(value=f"{self.temperature.get():.2f}")
        def update_temp_label(val): self.temp_display.set(f"{float(val):.2f}")
        ttk.Scale(c_frame, variable=self.temperature, from_=0.0, to=1.0, command=update_temp_label).grid(row=2, column=1, sticky="ew", padx=5)
        ttk.Label(c_frame, textvariable=self.temp_display, width=4).grid(row=2, column=2, sticky="w")

        a_frame = ttk.Frame(self)
        a_frame.pack(fill="x", padx=main_pad, pady=15)
        self.btn_start = ttk.Button(a_frame, text="START TRANSLATION", command=self.start_translation)
        self.btn_start.pack(side="left", fill="x", expand=True, ipady=10, padx=(0,10))
        self.btn_stop = ttk.Button(a_frame, text="STOP", command=self.stop_translation, state="disabled", width=15)
        self.btn_stop.pack(side="right", fill="x", ipady=10)

        p_frame = ttk.Frame(self)
        p_frame.pack(fill="x", padx=main_pad, pady=5)
        ttk.Label(p_frame, textvariable=self.status_var, foreground=self.accent_color).pack(anchor="w")
        ttk.Progressbar(p_frame, variable=self.progress_var).pack(fill="x", ipady=2)
        
        l_frame = ttk.LabelFrame(self, text="LOG", padding=10)
        l_frame.pack(fill="both", expand=True, padx=main_pad, pady=(5,20))
        self.txt_console = scrolledtext.ScrolledText(l_frame, height=8, bg="#1e1e1e", fg="#00ff00", font=("Consolas", 9), borderwidth=0)
        self.txt_console.pack(fill="both", expand=True)
        
        threading.Thread(target=self._load_models_worker, daemon=True).start()

    def _load_models_worker(self):
        """Background thread to fetch models without freezing the GUI."""
        models = self.get_installed_models()
        # Schedule UI update on the main thread
        self.after(0, lambda: self._update_model_dropdowns(models))

    def _update_model_dropdowns(self, models):
        """Called by the background thread to safely update UI widgets."""
        # Safety fallback if no models returned
        if not models: models = ["None"]
        
        # --- 1. Update Primary Model Combobox ---
        self.cbox_primary['values'] = models
        
        # Intelligent Default Selection
        # We only auto-select if the current value is a placeholder
        current_p = self.model_primary.get()
        if current_p == "Loading..." or not current_p:
            # Priority 1: GPT-OSS (Best for STEM/Engineering)
            if any("gpt-oss" in m for m in models):
                self.model_primary.set(next((m for m in models if "gpt-oss" in m), ""))
            # Priority 2: TranslateGemma (Google's Specialist Model)
            elif any("translategemma" in m for m in models):
                self.model_primary.set(next((m for m in models if "translategemma" in m), ""))
            # Priority 3: First available alphabetical model
            elif models:
                self.model_primary.set(models[0])

        # --- 2. Update Secondary (Consultant) Combobox ---
        # Consultant mode is optional, so we always prepend "None"
        self.cbox_secondary['values'] = ["None"] + models
        
        current_s = self.model_secondary.get()
        if current_s == "Loading..." or not current_s:
            self.model_secondary.set("None")

        # --- 3. Connect Validation Listener (GUI Enhancement) ---
        # This binds the "Selection Changed" event to the validation function.
        # It ensures that when a user manually picks a model, we run the 
        # silent 1-token pre-warm check (validate_model_ready).
        self.cbox_primary.bind("<<ComboboxSelected>>", lambda e: self.validate_model_ready())

    def validate_model_ready(self):
        """Silent check to ensure model is loaded in VRAM."""
        model = self.model_primary.get()
        if not model or model == "None" or model == "Loading...": return
        
        def _warmup():
            try:
                # Update status without blocking
                self.after(0, lambda: self.status_var.set(f"Warming up {model}..."))
                
                # Run a 1-token generation to load model into VRAM
                ollama.generate(model=model, prompt="hi", options={'num_predict': 1})
                
                self.after(0, lambda: self.status_var.set("Ready."))
            except Exception as e:
                # If it fails, show error on main thread
                self.after(0, lambda: messagebox.showerror("Model Error", f"Could not load {model}: {e}"))
                self.after(0, lambda: self.status_var.set("Error loading model."))
                
        threading.Thread(target=_warmup, daemon=True).start()
			
    def browse_file(self):
        files = filedialog.askopenfilenames(filetypes=[("Word", "*.docx")])
        if files:
            self.selected_files = files
            self.file_path.set(files[0] if len(files) == 1 else f"({len(files)} files selected) - {files[0]}...")
            self.txt_console.delete(1.0, tk.END)
            self.progress_var.set(0)
            self.status_var.set("Ready to start.")
            self.log_message(f"-> Loaded {len(files)} file(s). Configured and ready.")

    def start_translation(self):
        target_files = getattr(self, 'selected_files', []) or ([self.file_path.get().replace('"', '')] if self.file_path.get() else [])
        if not target_files: return messagebox.showerror("Error", "Please select valid DOCX files.")
        if not self.model_primary.get(): return messagebox.showerror("Error", "Please select a Primary Translation Model.")

        sec_model = self.model_secondary.get()
        if sec_model and sec_model != "None":
            installed = self.get_installed_models()
            if not (sec_model in installed or f"{sec_model}:latest" in installed):
                if not messagebox.askyesno("Model Warning", f"Consultant '{sec_model}' not installed. Download now?"): return

        config = {
            'file_paths': target_files,
            'lang_in': self.lang_in.get(),
            'lang_out': self.lang_out.get(),
            'model_primary': self.model_primary.get(),
            'model_secondary': self.model_secondary.get(),
            'temperature': self.temperature.get(),
            'context_window': 10
        }

        self.txt_console.delete(1.0, tk.END)
        self.toggle_ui_state(True)
        self.engine = TranslationEngine(config, self.log_message, self.update_progress_bar)
        self.worker_thread = threading.Thread(target=self.run_worker)
        self.worker_thread.start()

    def log_message(self, msg):
        self.after(0, lambda: self.txt_console.insert(tk.END, f"[{datetime.datetime.now().strftime('%H:%M:%S')}] {msg}\n"))
        self.after(0, lambda: self.txt_console.see(tk.END))

    def update_progress_bar(self, current, total, msg, start_time=None):
        percent = min((current / total) * 100, 100) if total > 0 else 0
        
        eta_str = ""
        # Only calculate ETA if we have processed enough items (Wait for stability)
        if start_time and current > 5: 
            elapsed = time.time() - start_time
            if elapsed > 0.1: # Prevent division by zero or micro-timings
                rate = current / elapsed
                remaining_items = total - current
                
                if rate > 0:
                    eta_seconds = remaining_items / rate
                    # Create a friendly time string (e.g. 0:05:30)
                    time_str = str(datetime.timedelta(seconds=int(eta_seconds)))
                    eta_str = f" | ETA: {time_str}"
            
        # Schedule UI updates on the main thread
        self.after(0, lambda: self.progress_var.set(percent))
        self.after(0, lambda: self.status_var.set(f"{msg} ({int(percent)}%){eta_str}"))

    def toggle_ui_state(self, is_running):
        state = "disabled" if is_running else "normal"
        self.btn_start.config(state=state)
        self.btn_stop.config(state="normal" if is_running else "disabled")

    def run_worker(self):
        try: 
            self.engine.run()
        except Exception as e: 
            self.log_message(f"FATAL ERROR: {e}")
        finally: 
            # THREAD SAFETY: Schedule UI update on main thread
            self.after(0, lambda: self.toggle_ui_state(False))

    def stop_translation(self):
        if self.engine:
            self.log_message("Stopping translation... please wait.")
            self.engine.stop_flag = True

if __name__ == "__main__":
    app = TranslatorApp()
    app.mainloop()